### ISSUE TITLE
version 1.8.8 on a server has mcData.loginPacket return undefiend in default usage example

### ISSUE THREAD

**Issue by XFaonAE** [PrismarineJS/node-minecraft-protocol#890] opened 2021-08-18 22:45 UTC
[ ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.26.1
 - server: vanilla/spigot/paper Docs didnt say any think about this
 - node: 16.6.2

## Detailed description of a problem
A clear and concise description of what the problem is.

## Current code
```js
const mc = require('minecraft-protocol')
const Chunk = require('prismarine-chunk')('1.8.8')
const Vec3 = require('vec3')
const server = mc.createServer({
  'online-mode': true,
  encryption: true,
  host: '0.0.0.0',
  port: 1012,
  version: '1.8.8'
})
const mcData = require('minecraft-data')(server.version)
const loginPacket = mcData.loginPacket
const chunk = new Chunk()

console.log(loginPacket)

for (let x = 0; x < 16; x++) {
  for (let z = 0; z < 16; z++) {
    chunk.setBlockType(new Vec3(x, 100, z), mcData.blocksByName.grass_block.id)
    chunk.setBlockData(new Vec3(x, 100, z), 1)
    for (let y = 0; y < 256; y++) {
      chunk.setSkyLight(new Vec3(x, y, z), 15)
    }
  }
}

server.on('login', function (client) {
  client.write('login', {
    entityId: client.id,
    isHardcore: false,
    gameMode: 0,
    previousGameMode: 255,
    worldNames: loginPacket.worldNames,
    dimensionCodec: loginPacket.dimensionCodec,
    dimension: loginPacket.dimension,
    worldName: 'minecraft:overworld',
    hashedSeed: [0, 0],
    maxPlayers: server.maxPlayers,
    viewDistance: 10,
    reducedDebugInfo: false,
    enableRespawnScreen: true,
    isDebug: false,
    isFlat: false
  })
  client.write('map_chunk', {
    x: 0,
    z: 0,
    groundUp: true,
    biomes: chunk.dumpBiomes !== undefined ? chunk.dumpBiomes() : undefined,
    heightmaps: {
      type: 'compound',
      name: '',
      value: {} // Client will accept fake heightmap
    },
    bitMap: chunk.getMask(),
    chunkData: chunk.dump(),
    blockEntities: []
  })
  client.write('position', {
    x: 15,
    y: 101,
    z: 15,
    yaw: 137,
    pitch: 0,
    flags: 0x00
  })
})
```

## Expected behavior
loginPackets not to be undefiened

**Comment by u9g** [comment] 2021-08-18 22:45
the examples are only expected to work for the latest version of mc, you can try seeing when 1.9 came out and find the last commit before that and use that code.

**Comment by nickelpro** [comment] 2021-08-18 23:13
1.8 doesn't have a `loginPacket` json, because 1.8 doesn't support any of the fields the `loginPacket` json is necessary for. [Your login packet is structured incorrectly for 1.8](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.8/protocol.json#L554-L586), missing `levelType` and `difficulty` and including many fields that don't exist.

Not a bug, recommend closing.

**Comment by rom1504** [comment] 2021-08-19 13:20
https://github.com/PrismarineJS/flying-squid/blob/debb5fa6b800babfb62d29384a90e420522092ce/src/lib/plugins/login.js#L85 is how to send login whatever the version

**Closed** 2022-03-13 17:59 UTC
