### ISSUE TITLE
Update minecraft 1.19.4

### ISSUE THREAD

**Issue by khiempham06** [PrismarineJS/node-minecraft-protocol#1225] opened 2023-05-21 13:20 UTC
/home/user/BotGuard/BotGuard/node_modules/minecraft-protocol/src/createClient.js:29
  if (!mcData) throw new Error(`unsupported protocol version: ${optVersion}`)
               ^

Error: unsupported protocol version: 1.19.4
    at Object.createClient (/home/user/BotGuard/BotGuard/node_modules/minecraft-protocol/src/createClient.js:29:22)
    at Object.createBot (/home/user/BotGuard/BotGuard/node_modules/mineflayer/lib/loader.js:95:35)
    at Object.<anonymous> (/home/user/BotGuard/BotGuard/index.js:7:24)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47

**Comment by andriycraft** [comment] 2023-05-24 10:02
dupe of #1097

**Closed** 2023-06-04 07:42 UTC
