### ISSUE TITLE
"gulp" failing

### ISSUE THREAD

**Issue by beppe9000** [PrismarineJS/node-minecraft-protocol#190] opened 2015-07-10 21:56 UTC
I tried installing with `npm install minecraft-protocol` in a dir and got jumbo errors. Npm says I should report, and here i do:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'minecraft-protocol' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose install initial load of C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\package.json
5 verbose installManyTop reading scoped package data from C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules\minecraft-protocol\package.json
6 verbose installManyTop reading scoped package data from C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules\npm-debug.log\package.json
7 verbose installManyTop reading scoped package data from C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules\x\package.json
8 info package.json minecraft-protocol@0.14.0 license should be a valid SPDX license expression
9 verbose readDependencies loading dependencies from C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\package.json
10 verbose install minecraft-protocol is installed as 0.14.0
11 silly cache add args [ 'minecraft-protocol', null ]
12 verbose cache add spec minecraft-protocol
13 silly cache add parsed spec { raw: 'minecraft-protocol',
13 silly cache add   scope: null,
13 silly cache add   name: null,
13 silly cache add   rawSpec: 'minecraft-protocol',
13 silly cache add   spec: 'C:\\Users\\Administrator\\Documents\\Visual Studio 2013\\Projects\\Z1\\Z1\\bin\\Debug\\edge\\node_modules\\minecraft-protocol',
13 silly cache add   type: 'directory' }
14 verbose addLocalDirectory C:\Users\Administrator\AppData\Roaming\npm-cache\minecraft-protocol\0.14.0\package.tgz not in flight; packing
15 verbose tar pack [ 'C:\\Users\\Administrator\\AppData\\Roaming\\npm-cache\\minecraft-protocol\\0.14.0\\package.tgz',
15 verbose tar pack   'C:\\Users\\Administrator\\Documents\\Visual Studio 2013\\Projects\\Z1\\Z1\\bin\\Debug\\edge\\node_modules\\minecraft-protocol' ]
16 verbose tarball C:\Users\Administrator\AppData\Roaming\npm-cache\minecraft-protocol\0.14.0\package.tgz
17 verbose folder C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules\minecraft-protocol
18 info prepublish minecraft-protocol@0.14.0
19 verbose unsafe-perm in lifecycle true
20 info minecraft-protocol@0.14.0 Failed to exec prepublish script
21 error addLocalDirectory Could not pack C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules\minecraft-protocol to C:\Users\Administrator\AppData\Roaming\npm-cache\minecraft-protocol\0.14.0\package.tgz
22 error addLocal Could not install C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules\minecraft-protocol
23 verbose stack Error: minecraft-protocol@0.14.0 prepublish: `gulp`
23 verbose stack Exit status 1
23 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
23 verbose stack     at EventEmitter.emit (events.js:110:17)
23 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
23 verbose stack     at ChildProcess.emit (events.js:110:17)
23 verbose stack     at maybeClose (child_process.js:1015:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
24 verbose pkgid minecraft-protocol@0.14.0
25 verbose cwd C:\Users\Administrator\Documents\Visual Studio 2013\Projects\Z1\Z1\bin\Debug\edge\node_modules
26 error Windows_NT 6.2.9200
27 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "minecraft-protocol"
28 error node v0.12.6
29 error npm  v2.11.2
30 error code ELIFECYCLE
31 error minecraft-protocol@0.14.0 prepublish: `gulp`
31 error Exit status 1
32 error Failed at the minecraft-protocol@0.14.0 prepublish script 'gulp'.
32 error This is most likely a problem with the minecraft-protocol package,
32 error not with npm itself.
32 error Tell the author that this fails on your system:
32 error     gulp
32 error You can get their info via:
32 error     npm owner ls minecraft-protocol
32 error There is likely additional logging output above.
33 verbose exit [ 1, true ]
```

**Comment by roblabla** [comment] 2015-07-11 14:51
I cannot reproduce this issue, despite having the same nodejs and npm version, and being on Windows 8.1 (which should be close enough to your platform, only visible discrepency is you are running Win8).

I suggest you remove your `%USERPROFILE%/.npm` folder and try the installation again (that folder is a cache npm keeps to speed up installation). For some reason, your npm is trying to run the prepublish script when it clearly shouldn't be.

Please report if deleting the .npm folder worked :)

**Comment by roblabla** [comment] 2015-07-18 18:00
Closing. If you are still having the issue, please re-open.

**Closed by roblabla** 2015-07-18 18:00 UTC

**Comment by beppe9000** [comment] 2015-07-19 08:54
My os is windows server 2012. Maybe that would help understanding the problem. I was trying to get your package but I had found an alternative (a c# library).
