### ISSUE TITLE
[1.9 protocol inaccuracies] Disconnecting Clients

### ISSUE THREAD

**Issue by annoyingcalc** [PrismarineJS/node-minecraft-protocol#385] opened 2016-03-02 17:48 UTC
A few bugs I've found are:

Loading a painting (Just place one) will kick the client and not let them back on until the entity is removed.

When a client sends update_sign to the server, proxy gives an error and then doesn't accept any more packets from the client.

(This bug is unconfirmed, and speculated by EgoScio): When you join a server that has a custom resource packet, that will disconnect the client immediately.

**Comment by rom1504** [comment] 2016-03-02 18:41
* Loading a painting  : confirmed and fixed
* update_sign : I can't reproduce (may have been fixed by load painting fix, not sure how signs work)
* custom resource packet : how can I test this ?

**Comment by rom1504** [comment] 2016-03-02 18:43
Loading a painting fix published as 0.19.4, try if it works for you, and tell me if you can reproduce the other problems ;)

**Comment by vincss** [comment] 2016-03-03 10:10
I've updated my server to 1.9, but I can't get the version 0.19.4 by updating with :
npm update minecraft-protocol --save
Is it normal ? How can I can a working 1.9 version by npm ?

**Comment by rom1504** [comment] 2016-03-03 10:12
@vincss what do you mean you "can't get the version 0.19.4" ? what did the npm command return ?

be aware that nmp is now cross-version and the default version is still 1.8, if you want to use 1.9, you need to say it with the "version":"1.9" option in createClient or createServer

**Comment by vincss** [comment] 2016-03-03 10:22
By npm, my version stays at :   "minecraft-protocol": "^0.16.6",
Which doesn't support Minecraft 1.9 I think.

This is what I'm using the plugin for :
https://www.spigotmc.org/resources/sleepingserverstarter.15720/
https://github.com/vincss/mcsleepingserverstarter

**Comment by rom1504** [comment] 2016-03-03 10:24
Not sure what "npm update" does. I think it was broken for at least a few releases of npm.

Just update minecraft-protocol version in your package.json and do npm install

**Comment by vincss** [comment] 2016-03-03 12:50
Ok, it's working. Thanks.

**Comment by rom1504** [comment] 2016-03-04 09:53
@annoyingcalc so, does everything work for you in the end ?

**Comment by rom1504** [comment] 2016-03-21 09:19
fixed

**Closed by rom1504** 2016-03-21 09:19 UTC
