### ISSUE TITLE
Console error with mineflayer bot in 1.19.2

### ISSUE THREAD

**Issue by ShortByte** [PrismarineJS/node-minecraft-protocol#1048] opened 2022-12-14 23:48 UTC
[ x ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.36.2
 - server: spigot 1.19.2
 - node: 16.15.1
 - mineflayer: master

## Detailed description of a problem
I just want to let a bot with Mineflayer join a 1.19.2 server and after logging in the following error occurs and the bot gets a timeout.

#### Console error:
```bash
TypeError: Serialization error for play.toServer : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')
    at Object.previousMessages (eval at compile (F:\Github\test\node_modules\protodef\src\compiler.js:258:12), <anonymo    at Object.packet_chat_command (eval at compile (F:\Github\test\node_modules\protodef\src\compiler.js:258:12), <anonymous>:559:37)
    at eval (eval at compile (F:\Github\test\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1186:64)
    at packet (eval at compile (F:\Github\test\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1235:9)
    at CompiledProtodef.sizeOf (F:\Github\test\node_modules\protodef\src\compiler.js:89:14)
    at e.message (F:\Github\test\node_modules\protodef\src\compiler.js:96:40)
    at tryCatch (F:\Github\test\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (F:\Github\test\node_modules\protodef\src\compiler.js:96:20)
    at Serializer.createPacketBuffer (F:\Github\test\node_modules\protodef\src\serializer.js:12:23)
    at Serializer._transform (F:\Github\test\node_modules\protodef\src\serializer.js:18:18) {
  field: 'play.toServer'
}
```

## Current code
```js
const bot = createBot({
  host: '',
  port: 25565,
  version: '1.19.2',
  username: 'HIDDEN',
  password: 'HIDDEN',
  auth: 'microsoft'
});

bot.on('error', (error) => {
  console.log(`Error: ${error.message}`);
});

bot.on('end', (reason) => {
  console.log(`Bot stopped. (Reason: ${reason})`);
});

bot.once('spawn', () => {
  console.log(`Bot logged in! (Username: ${bot.username})`);
});
```

## Expected behavior
No errors.

## Additional context
Default spigot 1.19.2 server, `online-mode=false`, no proxy.

**Comment by Mqrco0** [comment] 2022-12-27 19:14
I have the same issue.

**Comment by frej4189** [comment] 2022-12-27 20:26
Mineflayer does not support 1.19.2

**Comment by rom1504** [comment] 2023-01-07 21:54
duplicate of #1046

**Closed by rom1504** 2023-01-07 21:54 UTC
